### ISSUE TITLE
title change

### ISSUE THREAD

**Issue by marcblanchet** [marcblanchet/draft-deepspace-ip-architecture#1]
Title was created by cutting words from the re-assessment document title. However, having "The ..." at the beginning may be interpreted as too much even if it was not intentional. (English as non-native language of the first author). 
Suggest to change from "The IP Protocol Stack in Deep Space: Architecture" to "IP protocol Stack ..." or "An Architecture of the IP protocol stack in deep space"?

**Comment by tony1athome** [comment]
Suggestion: An Architecture for IP in Deep Space

**Comment by marcblanchet** [comment]
Much better. Do you think the current title could be seen as enough offensive to require a -01 right now?

**Comment by tony1athome** [comment]
No, not at all. Offensive would require the use of racial epithets.
